name: adaptive_grid
description: A lightweight Flutter package that creates fully responsive, dynamic grids.
version: 1.0.3
repository: https://github.com/MajdHajHmidi/adaptive_grid.git
homepage: https://github.com/MajdHajHmidi/adaptive_grid

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.8

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
